In [22]:
import pandas as pd
import numpy as np
pd.options.display.max_columns = 999
df = pd.read_csv('../../dsg/demand_anonymized_20170802.csv',sep=';', parse_dates=['Month'])
df.head()

,ID,First_MAD,SalOrg,DC,Ship_To,ordre,Plant,Material,ItemCat,OrderQty,LT,LogABC,MOQ,ROP,SafetyStk,PL,MktABC,SubFct,Gross_Weight,Length,Width,Height,Volume,Gamma,Manufacturer,Business,Month,CBO_CBO_Qty_Shortage,Age_ZN_ZI_years,DP_FAMILY_CODE,PRODUCT_STATUS,ORIGINAL_SUPPLIER,SUBRANGE,Comp_reference_number,Name_Of_Competitor,COMP_PRICE_MIN,COMP_PRICE_AVG,COMP_PRICE_MAX,PRICE,NEAREST_COMP_PRICE_MIN,NEAREST_COMP_PRICE_MAX
0,2724174,2014-09-12,yqSu,TUiR,MsHvUF,ggT8Bq,vP6T,iR1zr2,lvOi,1,28.0,Nc4e,72.0,0.0,21.0,NmYB,9rfJ,PjXe,0.006299,0.643863,2.148148,0.693069,0.000480,syni,1nVy21,32af,2014-09-01,NaN,NaN,QIzS,TiQl,X6qzbY,qmsY,1.0,1.0,136.800,136.800000,136.80,152.95,136.80,136.80
1,2325939,2016-02-12,yqSu,csdY,BA5kLC,AIZGVy,vP6T,mD2b7j,lvOi,10,35.0,hfuf,300.0,0.0,87.0,c2Z5,vegq,PjXe,0.000693,0.281690,0.296296,3.613861,0.000151,syni,1nVy21,otZd,2016-02-01,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1836800,2013-05-24,U12J,TUiR,MBZhLQ,8Z4g83,Cisr,AjywTn,lvOi,2,28.0,Nc4e,12.0,0.0,69.0,ss6l,vegq,PjXe,0.038961,1.529175,2.518519,0.653465,0.001261,MYF4,o86vTw,32af,2013-05-01,NaN,2.493151,W2Bc,TiQl,SXlc2j,bUkB,3.0,2.0,411.939,677.394667,830.28,908.60,830.28,830.28
3,2820654,2012-07-12,yqSu,csdY,9Co4iE,RNuiEu,vP6T,DPiXfc,lvOi,10,35.0,Nc4e,450.0,0.0,148.0,c2Z5,vegq,PjXe,0.000682,0.241449,4.814815,0.247525,0.000144,syni,1nVy21,otZd,2012-07-01,NaN,NaN,zAA4,TiQl,Rmt5iw,5cy5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5579286,2012-02-29,OQfZ,TUiR,88lPvN,KPTgL7,9O7Z,tOsuQV,lvOi,6,28.0,Nc4e,460.0,0.0,500.0,c2Z5,9rfJ,PjXe,0.000693,0.261569,4.481481,0.173267,0.000100,9AXw,OEScPd,otZd,2012-02-01,NaN,NaN,yZYX,TiQl,ikezPZ,1ftA,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
import pandas as pd
df = pd.read_csv('rnn.csv')
df

            ID      demand
0            0    0.993651
1            1    0.000000
2            2    0.000000
3            3    0.000000
4            4    0.000000
5            5    0.000000
6            6    0.000000
7            7    0.000000
8            8    0.000000
9            9  268.780121
10          10    0.000000
11          11    0.000000
12          12    0.000000
13          13    0.000000
14          14    0.000000
15          15    0.000000
16          16    0.000000
17          17    0.000000
18          18    0.000000
19          19    0.000000
20          20   21.553785
21          21    0.000000
22          22    0.000000
23          23    0.000000
24          24    0.000000
25          25    0.000000
26          26    0.000000
27          27    0.000000
28          28    0.000000
29          29    0.000000
...        ...         ...
115998  115998    0.000000
115999  115999    0.583485
116000  116000    0.000000
116001  116001    0.000000
116002  116002    0.000000
116003  116003    0.000000
116004  116004    0.000000
116005  116005    0.000000
116006  116006    0.000000
116007  116007    0.000000
116008  116008    0.000000
116009  116009    0.000000
116010  116010    0.000000
116011  116011    5.106915
116012  116012    0.000000
116013  116013    0.000000
116014  116014   26.701857
116015  116015    0.000000
116016  116016    7.998930
116017  116017    0.000000
116018  116018    0.000000
116019  116019    0.000000
116020  116020    0.000000
116021  116021    0.000000
116022  116022    0.000000
116023  116023    0.000000
116024  116024  193.183655
116025  116025    0.000000
116026  116026    0.000000
116027  116027    0.000000

[116028 rows x 2 columns]

In [2]:
def get_cathegorical_stats(df, column_name):
    final_df = df.groupby(['SalOrg', 'Material', 'Month', column_name])['OrderQty']
    final_df_sum = final_df.sum().unstack(column_name).add_prefix(column_name + 'sum_')
    final_df_count = final_df.size().unstack(column_name).add_prefix(column_name + 'count_')
    final_df_mean = final_df.mean().unstack(column_name).add_prefix(column_name + 'mean_')
    final_df_max = final_df.max().unstack(column_name).add_prefix(column_name + 'max_')
    final_df_min = final_df.min().unstack(column_name).add_prefix(column_name + 'min_')
    final_df = final_df_sum.reset_index().merge(final_df_count.reset_index(), on = ['SalOrg', 'Material', 'Month'], copy = False)
    final_df = final_df.merge(final_df_mean.reset_index(), on = ['SalOrg', 'Material', 'Month'], copy = False)
    final_df = final_df.merge(final_df_max.reset_index(), on = ['SalOrg', 'Material', 'Month'], copy = False)
    final_df = final_df.merge(final_df_min.reset_index(), on = ['SalOrg', 'Material', 'Month'], copy = False)
    final_df = final_df.fillna(0)
    return final_df

In [3]:
def get_clustered_stats(df, column_name):
    final_df = df.groupby(['SalOrg', 'Month', column_name])['OrderQty']
    final_df_sum = final_df.sum().unstack(column_name).add_prefix(column_name + 'sum_')
    final_df_count = final_df.size().unstack(column_name).add_prefix(column_name + 'count_')
    final_df_mean = final_df.mean().unstack(column_name).add_prefix(column_name + 'mean_')
    final_df_max = final_df.max().unstack(column_name).add_prefix(column_name + 'max_')
    final_df_min = final_df.min().unstack(column_name).add_prefix(column_name + 'min_')
    final_df = final_df_sum.reset_index().merge(final_df_count.reset_index(), on = ['SalOrg', column_name, 'Month'], copy = False)
    final_df = final_df.merge(final_df_mean.reset_index(), on = ['SalOrg', column_name, 'Month'], copy = False)
    final_df = final_df.merge(final_df_max.reset_index(), on = ['SalOrg', column_name, 'Month'], copy = False)
    final_df = final_df.merge(final_df_min.reset_index(), on = ['SalOrg', column_name, 'Month'], copy = False)
    final_df = final_df.fillna(0)
    return final_df

In [4]:
def get_mean_stats(df, column_name):
    final_df = df.groupby(['SalOrg', 'Material', 'Month'])[column_name].mean().reset_index()
    return final_df

In [5]:
sum(df['DP_FAMILY_CODE'].isnull())

1952528

In [ ]:
get_clustered_stats(df,'DP_FAMILY_CODE')

In [ ]:
df = df.merge(get_mean_stats(df,'LT'), on = ['SalOrg', 'Material', 'Month'], copy = False)

In [ ]:
df = df.merge(get_mean_stats(df,'MOQ'), on = ['SalOrg', 'Material', 'Month'], copy = False)

In [ ]:
df = df.merge(get_cathegorical_stats(df,'MktABC'), on = ['SalOrg', 'Material', 'Month'], copy = False)

In [ ]:
df = df.merge(get_cathegorical_stats(df,'DC'), on = ['SalOrg', 'Material', 'Month'], copy = False)

In [ ]:
import itertools
test = pd.read_csv('../../dsg/demand_anonymized_20170802.csv',sep=';')
eval_comb = test[['Material', 'SalOrg']]
eval_comb = list(set([tuple(x) for x in eval_comb.values]))

comb = list(itertools.product(*[eval_comb, list(df['Month'].unique())]))
comb = [(t[0], t[1], m) for t, m in comb]

series2 = pd.DataFrame(comb, columns=['Material', 'SalOrg', 'Month'])
series2 = series2.sort_values(by=['Month', 'SalOrg', 'Material' ])
series2 = series2.merge(df, on=['Month', 'Material', 'SalOrg'], how='left')
series2 = series2.fillna(0)

In [ ]:
df.head()

In [ ]:
series2.head()

In [29]:
df.shape

(5595701, 41)

In [69]:
df.head()

,ID,First_MAD,SalOrg,DC,Ship_To,ordre,Plant,Material,ItemCat,OrderQty,LT,LogABC,MOQ,ROP,SafetyStk,PL,MktABC,SubFct,Gross_Weight,Length,Width,Height,Volume,Gamma,Manufacturer,Business,Month,CBO_CBO_Qty_Shortage,Age_ZN_ZI_years,DP_FAMILY_CODE,PRODUCT_STATUS,ORIGINAL_SUPPLIER,SUBRANGE,Comp_reference_number,Name_Of_Competitor,COMP_PRICE_MIN,COMP_PRICE_AVG,COMP_PRICE_MAX,PRICE,NEAREST_COMP_PRICE_MIN,NEAREST_COMP_PRICE_MAX
0,2724174,2014-09-12,yqSu,TUiR,MsHvUF,ggT8Bq,vP6T,iR1zr2,lvOi,1,28.0,Nc4e,72.0,0.0,21.0,NmYB,9rfJ,PjXe,0.006299,0.643863,2.148148,0.693069,0.000480,syni,1nVy21,32af,2014-09-01,NaN,NaN,QIzS,TiQl,X6qzbY,qmsY,1.0,1.0,136.800,136.800000,136.80,152.95,136.80,136.80
1,2325939,2016-02-12,yqSu,csdY,BA5kLC,AIZGVy,vP6T,mD2b7j,lvOi,10,35.0,hfuf,300.0,0.0,87.0,c2Z5,vegq,PjXe,0.000693,0.281690,0.296296,3.613861,0.000151,syni,1nVy21,otZd,2016-02-01,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1836800,2013-05-24,U12J,TUiR,MBZhLQ,8Z4g83,Cisr,AjywTn,lvOi,2,28.0,Nc4e,12.0,0.0,69.0,ss6l,vegq,PjXe,0.038961,1.529175,2.518519,0.653465,0.001261,MYF4,o86vTw,32af,2013-05-01,NaN,2.493151,W2Bc,TiQl,SXlc2j,bUkB,3.0,2.0,411.939,677.394667,830.28,908.60,830.28,830.28
3,2820654,2012-07-12,yqSu,csdY,9Co4iE,RNuiEu,vP6T,DPiXfc,lvOi,10,35.0,Nc4e,450.0,0.0,148.0,c2Z5,vegq,PjXe,0.000682,0.241449,4.814815,0.247525,0.000144,syni,1nVy21,otZd,2012-07-01,NaN,NaN,zAA4,TiQl,Rmt5iw,5cy5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5579286,2012-02-29,OQfZ,TUiR,88lPvN,KPTgL7,9O7Z,tOsuQV,lvOi,6,28.0,Nc4e,460.0,0.0,500.0,c2Z5,9rfJ,PjXe,0.000693,0.261569,4.481481,0.173267,0.000100,9AXw,OEScPd,otZd,2012-02-01,NaN,NaN,yZYX,TiQl,ikezPZ,1ftA,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
series2.to_csv('full_data.csv')

In [72]:
from scipy.stats.stats import pearsonr   
def get_correlation(df, n_months, n_delay):
    
    train = df.groupby(['SalOrg', 'Month', 'Material'])['OrderQty'].apply(lambda x: x.sum()).reset_index()
    
    train['LaggedOrderQty'] = train.OrderQty.shift(12)
    train = train.fillna(0)
    train = train.sort_values(by=['SalOrg', 'Material','Month'])
    df_corr = train.groupby(['SalOrg', 'Material']).apply(lambda x: np.corrcoef(np.array(x['OrderQty']), np.array(x['LaggedOrderQty']))[0][1]).reset_index()
    df_corr.columns = ["SalOrg"] + ['Material'] + ['Corr']
    return df_corr

In [73]:
corr = get_correlation(df, 6, 12)
corr

/anaconda/envs/py35/lib/python3.5/site-packages/numpy/lib/function_base.py:3154: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar)
/anaconda/envs/py35/lib/python3.5/site-packages/numpy/lib/function_base.py:3088: RuntimeWarning: divide by zero encountered in double_scalars
  c *= 1. / np.float64(fact)
/anaconda/envs/py35/lib/python3.5/site-packages/numpy/lib/function_base.py:3088: RuntimeWarning: invalid value encountered in multiply
  c *= 1. / np.float64(fact)
/anaconda/envs/py35/lib/python3.5/site-packages/numpy/lib/function_base.py:3162: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/anaconda/envs/py35/lib/python3.5/site-packages/numpy/lib/function_base.py:3163: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]

      SalOrg Material      Corr
0       97LK   00IYcj -0.066272
1       97LK   00MFcK -0.023429
2       97LK   00Ok8y -0.101324
3       97LK   00W03x       NaN
4       97LK   00lqzT -0.061077
5       97LK   00mt9e  0.183622
6       97LK   02QhQT  0.318212
7       97LK   02jRc8  0.446814
8       97LK   0355Np  0.141408
9       97LK   03GYN7       NaN
10      97LK   03eCyI  0.004116
11      97LK   041azJ  0.627572
12      97LK   04ocTC -0.108432
13      97LK   055wMw       NaN
14      97LK   05Uaax  0.999841
15      97LK   06DLxB -0.108345
16      97LK   06DbDI -0.365914
17      97LK   06NbhW       NaN
18      97LK   06RPuo -0.075575
19      97LK   06yAAh -0.283267
20      97LK   07B7Wu  0.129908
21      97LK   07aiIn  0.468863
22      97LK   07czqW  1.000000
23      97LK   07wS1j -0.296311
24      97LK   096shV  0.123644
25      97LK   09HDUi  0.333290
26      97LK   09TqnP  0.048182
27      97LK   09tyFq -0.203407
28      97LK   09vEjr       NaN
29      97LK   0ARTTj -0.259354
...      ...      ...       ...
38646   yqSu   zsN8ea -0.052137
38647   yqSu   zsdbBU  0.042660
38648   yqSu   zswl5Y       NaN
38649   yqSu   ztFwGT       NaN
38650   yqSu   ztWKq4  0.194545
38651   yqSu   ztbaRZ -0.015683
38652   yqSu   ztx5r8  0.258383
38653   yqSu   zu5Q3n -0.151619
38654   yqSu   zuDihg  0.203447
38655   yqSu   zuZp2B       NaN
38656   yqSu   zuhMcj -0.109126
38657   yqSu   zukayj  0.146034
38658   yqSu   zvohJH  0.123367
38659   yqSu   zvpaxW  0.192651
38660   yqSu   zw6W1G  0.122870
38661   yqSu   zwvoAw -0.052080
38662   yqSu   zxEnui       NaN
38663   yqSu   zxHh8w  0.134775
38664   yqSu   zxLvX7 -0.245003
38665   yqSu   zy4aqs  0.066318
38666   yqSu   zyEgcF -0.123436
38667   yqSu   zyJIlV -0.238946
38668   yqSu   zyJT3o       NaN
38669   yqSu   zyiLsd       NaN
38670   yqSu   zyus5p  0.017180
38671   yqSu   zyylEU       NaN
38672   yqSu   zzOfA5  0.167338
38673   yqSu   zzYnFP       NaN
38674   yqSu   zzgzni       NaN
38675   yqSu   zzlMo7 -0.132266

[38676 rows x 3 columns]

In [56]:
corr

[]